import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ProjectStatusForm } from '@/components/admin/project-status-form';
import { requireRole } from '@/lib/supabase/authorization';

export default async function AdminSubmissionPage({ params }: { params: { id: string } }) {
  const { supabase } = await requireRole('admin');
  const { data: submission } = await supabase.from('form_submissions').select('id, business_name, contact_name, contact_email, contact_phone, project_status, created_at, submitted_at, template_id, user_id').eq('id', params.id).maybeSingle();
  if (!submission) notFound();
  const [{ data: answers }, { data: template }, { data: notes }, { data: files }] = await Promise.all([
    supabase.from('form_answers').select('id, answer_text, answer_json, question_id').eq('submission_id', submission.id),
    submission.template_id ? supabase.from('form_templates').select('name').eq('id', submission.template_id).maybeSingle() : Promise.resolve({ data: null }),
    supabase.from('project_notes').select('id, content, created_at, author_id').eq('submission_id', submission.id).order('created_at', { ascending: false }),
    supabase.from('submission_files').select('id, filename').eq('submission_id', submission.id).order('uploaded_at', { ascending: false }),
  ]);
  const questionIds = answers?.map((answer) => answer.question_id).filter((id): id is string => Boolean(id)) ?? [];
  const { data: questions } = questionIds.length ? await supabase.from('form_questions').select('id, label').in('id', questionIds) : { data: [] };
  const labels = new Map((questions ?? []).map((question) => [question.id, question.label]));

  return <main className="mx-auto max-w-6xl px-6 py-10"><Link href="/admin" className="text-sm font-semibold text-[#7C3AED] hover:text-[#5B21B6] hover:underline">← Back to submissions</Link><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_360px]"><div><div className="card"><p className="text-sm font-semibold text-[#D4AF37]">{template?.name ?? 'Project request'}</p><h1 className="mt-2 text-3xl font-bold">{submission.business_name || 'Untitled project'}</h1><p className="mt-2 text-sm text-slate-500">Client ID: {submission.user_id}</p><dl className="mt-7 grid gap-5 sm:grid-cols-3"><div><dt className="text-xs font-semibold uppercase text-slate-500">Contact</dt><dd className="mt-1">{submission.contact_name || '—'}</dd></div><div><dt className="text-xs font-semibold uppercase text-slate-500">Email</dt><dd className="mt-1 break-all">{submission.contact_email || '—'}</dd></div><div><dt className="text-xs font-semibold uppercase text-slate-500">Phone</dt><dd className="mt-1">{submission.contact_phone || '—'}</dd></div></dl></div><div className="card mt-6"><h2 className="text-xl font-bold">Complete requirements</h2><div className="mt-5 divide-y">{answers?.length ? answers.map((answer) => <div key={answer.id} className="py-4 first:pt-0"><p className="text-sm font-semibold text-slate-600">{labels.get(answer.question_id ?? '') ?? 'Requirement'}</p><p className="mt-1 whitespace-pre-wrap text-sm">{Array.isArray(answer.answer_json) ? answer.answer_json.join(', ') : answer.answer_text || '—'}</p></div>) : <p className="text-sm text-slate-600">No answers saved.</p>}</div>{files?.length ? <div className="mt-8 border-t pt-6"><h3 className="font-semibold">Uploaded files</h3><ul className="mt-3 space-y-2">{files.map((file) => <li key={file.id}><a className="text-sm font-semibold text-[#7C3AED] hover:text-[#5B21B6] hover:underline" href={`/api/submissions/${submission.id}/files/${file.id}`}>{file.filename}</a></li>)}</ul></div> : null}</div></div><div><ProjectStatusForm id={submission.id} initialStatus={submission.project_status} /><section className="card mt-6"><h2 className="text-xl font-bold">Internal notes</h2><div className="mt-4 divide-y">{notes?.length ? notes.map((note) => <article key={note.id} className="py-3 first:pt-0"><p className="whitespace-pre-wrap text-sm text-slate-700">{note.content}</p><p className="mt-2 text-xs text-slate-500">{new Date(note.created_at).toLocaleString()}</p></article>) : <p className="text-sm text-slate-600">No internal notes yet.</p>}</div></section></div></div></main>;
}
